// <auto-generated />
using BuyBox.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuyBox.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240101070221_SeedCategoryTable")]
    partial class SeedCategoryTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.4.23259.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BuyBox.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Sand"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Brick"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Blue metal"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "AAC Block"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Cement"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Block Paste"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
