// <auto-generated />
using BuyBox.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuyBox.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240103181349_addProductstoDb")]
    partial class addProductstoDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.4.23259.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BuyBox.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Sand"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Brick"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Blue metal"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "AAC Block"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Cement"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Block Paste"
                        });
                });

            modelBuilder.Entity("BuyBox.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This is an regular brick",
                            ListPrice = 12.0,
                            Price = 11.0,
                            Price100 = 8.0,
                            Price50 = 10.0,
                            Title = "Regular Brick"
                        },
                        new
                        {
                            Id = 2,
                            Description = "This is an Premium brick",
                            ListPrice = 15.0,
                            Price = 14.0,
                            Price100 = 10.0,
                            Price50 = 12.0,
                            Title = "Premium Brick"
                        },
                        new
                        {
                            Id = 3,
                            Description = "This is M-sand used for building purpose",
                            ListPrice = 70.0,
                            Price = 65.0,
                            Price100 = 60.0,
                            Price50 = 65.0,
                            Title = "M-Sand"
                        },
                        new
                        {
                            Id = 4,
                            Description = "This is P-sand used for building purpose",
                            ListPrice = 60.0,
                            Price = 60.0,
                            Price100 = 50.0,
                            Price50 = 55.0,
                            Title = "P-Sand"
                        },
                        new
                        {
                            Id = 5,
                            Description = "This is River-sand used for building purpose",
                            ListPrice = 110.0,
                            Price = 110.0,
                            Price100 = 100.0,
                            Price50 = 105.0,
                            Title = "River-Sand"
                        },
                        new
                        {
                            Id = 6,
                            Description = "This is Blue Metal used for building purpose",
                            ListPrice = 110.0,
                            Price = 110.0,
                            Price100 = 100.0,
                            Price50 = 105.0,
                            Title = "Blue Metal"
                        },
                        new
                        {
                            Id = 7,
                            Description = "This is AAC Block used for building purpose",
                            ListPrice = 60.0,
                            Price = 60.0,
                            Price100 = 52.0,
                            Price50 = 55.0,
                            Title = " 4 inch AAC Block"
                        },
                        new
                        {
                            Id = 8,
                            Description = "This is AAC Block used for building purpose",
                            ListPrice = 60.0,
                            Price = 60.0,
                            Price100 = 52.0,
                            Price50 = 55.0,
                            Title = " 6 inch AAC Block"
                        },
                        new
                        {
                            Id = 9,
                            Description = "This is AAC Block used for building purpose",
                            ListPrice = 60.0,
                            Price = 60.0,
                            Price100 = 52.0,
                            Price50 = 55.0,
                            Title = " 9 inch AAC Block"
                        },
                        new
                        {
                            Id = 10,
                            Description = "This is best quality cement used for building purpose",
                            ListPrice = 420.0,
                            Price = 420.0,
                            Price100 = 410.0,
                            Price50 = 415.0,
                            Title = "Coromental Cement"
                        },
                        new
                        {
                            Id = 11,
                            Description = "This is best quality cement used for building purpose",
                            ListPrice = 400.0,
                            Price = 400.0,
                            Price100 = 390.0,
                            Price50 = 395.0,
                            Title = "Priya Cement"
                        },
                        new
                        {
                            Id = 12,
                            Description = "This is best quality AAC BLock paste used for building purpose",
                            ListPrice = 400.0,
                            Price = 400.0,
                            Price100 = 390.0,
                            Price50 = 395.0,
                            Title = "AAC block Paste"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
